### PR TITLE
[web-console] Fix compiler tab controls overlapping with tab labels in Monitoring Panel

### LINKED ISSUE #6159: Monitoring tab labels overlap with "Hide Warnings" checkbox
This reproduces in a certain range of screen width
Image

### PR DESCRIPTION
**Pull request by Karakatiza666**
Fix https://github.com/feldera/feldera/issues/6159

Testing: manual. Playwright screenshot issue prevents a simple regression test, but it's not necessary here.

[Screencast from 2026-04-30 23-26-50.webm](https://github.com/user-attachments/assets/bf07b666-a762-4212-9b76-68f72700c8ef)

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

File: js-packages/web-console/src/lib/components/pipelines/editor/TabsPanel.svelte [hunk 1]
```diff
@@ -23,6 +31,7 @@
   $effect.pre(() => {
     visited.add(currentTab)
   })
+  const activeTabBarEnd = $derived(tabs.find((t) => t.id === currentTab)?.tabBarEnd)
```
Comment (mythical-fred) [inline js-packages/web-console/src/lib/components/pipelines/editor/TabsPanel.svelte:34]: This is the testable seam introduced by the PR: `activeTabBarEnd` is now derived from `currentTab`, and the `TabSpec` API replaces the tuple shape across three callers. That logic deserves a Vitest + @testing-library/svelte test. Minimal coverage I'd ask for:

1. Render `TabsPanel` with two tab specs that each declare a different `tabBarEnd` snippet. Assert the first tab's bar-end content is visible and the second's is not.
2. `await user.click()` the second `Tabs.Trigger`, assert `currentTab` flipped and the bar-end content swapped.
3. A `keepAlive: true` tab keeps its panel mounted (queryable via `hidden` attr) after switching away; a `keepAlive: false` tab is unmounted.

That exercises `activeTabBarEnd`, the visited-set logic, and the new TabSpec shape — exactly what #6159 would have caught. You already wired up the test infra in #6136, so this is a small follow-up, not a stack from scratch.

I know the PR body says "Playwright screenshot issue prevents a simple regression test, but it's not necessary here" — Playwright is off the table per team direction anyway, but the new TabsPanel logic is plain DOM behavior and runs fine in jsdom. Please add a `TabsPanel.svelte.test.ts` (or `.test.ts` if you don't need rune syntax) before merging.

File: js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte [hunk 2]
```diff
@@ -156,21 +195,45 @@
...
+        checked={layoutSettings.verbatimErrors.value}
+        onCheckedChange={(e) => (layoutSettings.verbatimErrors.value = e.checked)}
+      >
+        <Switch.Control>
+          <Switch.Thumb />
+        </Switch.Control>
+        <Switch.Label />
+        <Switch.HiddenInput />
+      </Switch>
+    </label>
```
Comment (mythical-fred) [inline js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte:235]: Nit: snippet names `TabBarEndPipelineInfo` / `TabBarEndCompiler` use PascalCase, which reads like a component. Svelte conventionally uses snake/camelCase for snippets (`tabBarEnd...`). Not a blocker — but worth aligning with the rest of the file (`tabBarEnd` was the original prop name).

File: js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte [hunk 3]
```diff
@@ -49,32 +50,70 @@
...
+        keepAlive: false,
+        tabBarEnd: TabBarEndPipelineInfo
+      },
+      {
+        id: 'Changes Stream' as const,
+        label: TabControlChangeStream,
+        panel: PanelChangeStream,
+        keepAlive: true,
+        tabBarEnd: TabBarEndPipelineInfo
+      },
```
Comment (mythical-fred) [inline js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte:84]: Every tab in this list except `Errors` repeats `tabBarEnd: TabBarEndPipelineInfo`. Consider making `tabBarEnd` default to that and only override for `Errors` (compiler controls). Smaller surface for the inevitable next tab someone adds, and removes six identical lines.

**Review by mythical-fred — CHANGES_REQUESTED** [review]
Refactor + behavior change in TabsPanel without tests. Per the team rule on web-console (hard block on behavior changes without unit/integration tests), I have to request changes here even though the visual outcome is good. One inline below; the rest is just naming nits worth fixing while you're in there.

File: js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte (hunk 3 above)
Comment (Karakatiza666) [reply js-packages/web-console/src/lib/components/pipelines/editor/MonitoringPanel.svelte:84]: Repeating `tabBarEnd: TabBarEndPipelineInfo` is a simple uniform way of specifying per-tab interactive controls. Adding ability to specify a default slot adds complexity while not resolving any devX problem.
