### PR TITLE
Fix a bug in the text output that sometimes doesn't send the result headers

### LINKED ISSUE #2506: Visualize empty output of an ad hoc query
When the result of a query is empty, we produce empty output:

```
localhost:8080/demo> select * from red_transactions where customer_id = 100001;


localhost:8080/demo>
```

It would be better to show an empty table instead:

```
localhost:8080/demo> select * from red_transactions where customer_id = 100001;

+---------------------+-------+-------------+-------+--------------+--------------------+
| ts                  | amt   | customer_id | state | out_of_state | out_of_state_count |
+---------------------+-------+-------------+-------+--------------+--------------------+
+---------------------+-------+-------------+-------+--------------+--------------------+

localhost:8080/demo>
```

### PR DESCRIPTION
**Pull request by gz**
This can happen if dataframe didn't produce any record batches in the async execution. Which we didn't account for in the output logic.

Fixes #2506

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]
The pipeline should always produce an empty zset. There should always exist an output for every view. The iterator over that zset will not make any steps, though

**Comment by gz** [comment]
If the query plan just iterates our spine, it does indeed send a header, but if there is postprocessing in datafusion such as filters etc. it can happen that no result is yielded anymore. This is also described in the bug report that mentions this doesn't always happen.

**Comment by mihaibudiu** [comment]
Then this fix may be wrong too. You have to feed an empty table to your query. Do not assume that the result of the query is empty just because the input is empty

**Comment by gz** [comment]
This fix is still correct I believe. This particular case mentioned in the bug report we actually feed the entire view (aka many batches from dbsp to datafusion). But the result set of datafusion is a rust async iterator which is (correctly) empty and doesn't yield anything if we don't have any results to output. Note that this particular bug is only a problem when we output text and expect a header, e.g., json doesn't need a record header and parquet already added the header during initial file creation. I could've sent the header upfront as well in the text output, but I found it's nicer to send the header together with the first batch of data as it accounts for sizing each column correctly so it aligns with the data rows.

**Comment by gz** [comment]
In fact, I think it might be right to not send an empty batch in our datafusion table provider if the result is empty. I'll check what they expect from the table implementation.

**Review by ryzhyk — APPROVED** [review]
fixes the problem for me

File: crates/adapters/src/adhoc/mod.rs [hunk 1]
```diff
@@ -108,6 +110,27 @@ pub async fn stream_adhoc_result(
                             yield format!("ERROR: {}", e).into();
                             return;
                         }
+                    };
+
+                    // For some queries df.execute_stream() won't yield any batches
+                    // in case there aren't any results. When this happens we neve send the headers.
```
Comment (lalithsuresh) [inline crates/adapters/src/adhoc/mod.rs:116]: never
