### PR TITLE
[SQL] Fix incorrect conversion of long intervals to integers

### LINKED ISSUE #5894: [SQL] cannot find function `cast_to_i8_LongInterval_YEARS`
**Environment:** 

https://try.feldera.com/

**SQL program:** 

CREATE VIEW cast_032 AS SELECT CAST(INTERVAL '1' YEAR AS TINYINT)

**Error message:**

error[E0425]: cannot find function `cast_to_i8_LongInterval_YEARS` in this scope
    --> crates/feldera_pipe_operator_098c5ac7854648a5/src/lib.rs:72:104
     |
  72 | ..., &sourceMap, cast_to_i8_LongInterval_YEARS(LongInterval::from_months(12)))));
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `cast_to_VN_LongInterval_YEARS`
     |
    ::: /home/ubuntu/feldera/crates/sqllib/src/casts.rs:3591:1
     |
3591 | cast_variant!(LongInterval_YEARS, LongInterval, LongInterval);
     | ------------------------------------------------------------- similarly named function `cast_to_VN_LongInterval_YEARS` defined here
error: could not compile `feldera_pipe_operator_098c5ac7854648a5` (lib) due to 1 previous error

### LINKED ISSUE #5895: [SQL]  cannot find function `cast_to_i32_LongInterval_MONTHS`
Very similar to [(https://github.com/feldera/feldera/issues/5894)]

**Environment:**

https://try.feldera.com/

**SQL program:**

CREATE VIEW cast_034 AS SELECT CAST(INTERVAL '1000' MONTH AS INT);

**Error message:**

error[E0425]: cannot find function `cast_to_i32_LongInterval_MONTHS` in this scope
    --> crates/feldera_pipe_operator_18c22e0a3a8bbd0e/src/lib.rs:72:104
     |
  72 | ...&sourceMap, cast_to_i32_LongInterval_MONTHS(LongInterval::from_months(1000)))));
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `cast_to_i64_LongInterval_MONTHS`
     |
    ::: /home/ubuntu/feldera/crates/sqllib/src/casts.rs:1941:1
     |
1941 | pub fn cast_to_i64_LongInterval_MONTHS(value: LongInterval) -> SqlResult<i64> {
     | ----------------------------------------------------------------------------- similarly named function `cast_to_i64_LongInterval_MONTHS` defined here
error: could not compile `feldera_pipe_operator_18c22e0a3a8bbd0e` (lib) due to 1 previous error

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #5894 
Fixes #5895

## Checklist

- [x] Unit tests added/updated

### CODE REVIEW

**Comment by mihaibudiu** [comment]
@wilmaontherun you can check the unit tests at the end to check that the issues are solved.

File: crates/sqllib/src/casts.rs [hunk 1]
```diff
@@ -1739,212 +1739,103 @@ pub fn cast_to_i64_Weight(w: Weight) -> SqlResult<i64> {
...
-cast_function!(u64, u64, ShortInterval_MINUTES, ShortInterval);
-cast_function!(u8, u8, ShortInterval_SECONDS, ShortInterval);
-cast_function!(u16, u16, ShortInterval_SECONDS, ShortInterval);
-cast_function!(u32, u32, ShortInterval_SECONDS, ShortInterval);
-cast_function!(u64, u64, ShortInterval_SECONDS, ShortInterval);
-
 #[doc(hidden)]
-pub fn cast_to_i64_LongInterval_YEARS(value: LongInterval) -> SqlResult<i64> {
-    Ok(value.months() as i64)
+pub fn cast_to_u64_LongInterval_YEARS(value: LongInterval) -> SqlResult<u64> {
```
Comment (mythical-fred) [inline crates/sqllib/src/casts.rs:1812]: Inconsistency with the other unsigned casts: `cast_to_u8_LongInterval_YEARS`, `cast_to_u16_…`, and `cast_to_u32_…` all go through `cast_to_uN_i32(value.years())`, which uses `i32::try_from` / `u8::try_from` and returns an error for negative values. This function uses `value.years() as u64` instead, which sign-extends: `-1i32 as u64` is `18446744073709551615`, not an error. Should use `cast_to_u64_i32(value.years())` for consistency and safety.

File: crates/sqllib/src/casts.rs [hunk 2]
```diff
@@ -1739,212 +1739,103 @@ pub fn cast_to_i64_Weight(w: Weight) -> SqlResult<i64> {
...
+    Ok(value.years() as u64)
 }
 
 #[doc(hidden)]
-pub fn cast_to_i64_LongInterval_MONTHS(value: LongInterval) -> SqlResult<i64> {
-    Ok(value.months() as i64)
+pub fn cast_to_u64_LongInterval_MONTHS(value: LongInterval) -> SqlResult<u64> {
```
Comment (mythical-fred) [inline crates/sqllib/src/casts.rs:1817]: Same issue: `value.months() as u64` silently wraps negative months to a huge `u64`. Use `cast_to_u64_i32(value.months())` to match the overflow-checked pattern used by `u8`/`u16`/`u32`.
