### PR TITLE
[SQL] Improve code generation for functions that use Regex and Timezone

### LINKED ISSUE #6035: [SQL/DOCS]   Clarification is need: TIMESTAMP - TIMESTAMP is rejected by compiler
Component: SQL / datetime docs — https://docs.feldera.com/sql/datetime

Summary:

The datetime reference page documents (TIMESTAMP - TIMESTAMP) shortInterval and (TIMESTAMP -
TIMESTAMP) long Interval as valid arithmetic. The Feldera compiler rejects both forms.

  Reproduction:

  CREATE TABLE t (ts1 TIMESTAMP, ts2 TIMESTAMP);
  CREATE MATERIALIZED VIEW v AS SELECT ts1 - ts2 AS diff FROM t;

  Expected (per docs): compiles, returns INTERVAL.

  Actual compiler error:
  Cannot apply '-' to arguments of type '<TIMESTAMP(6)> - <TIMESTAMP(6)>'.

Image

### LINKED ISSUE #6039: [SQL] Improve evaluation of parsing timezones and regex
Several functions in SQL take as arguments regex or timezone objects represented as varchar values. If these values are constant they should be parsed and validated only once.

To some degree we do this already for regexp functions, but the implementation can be streamlined.

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #6039
Fixes #6035

There are a few other small commits.

The most important change is to change the generated code from:

```Rust
fn convert_timezone(tz: SqlString, ...) -> Option<Timestamp> {
  let t = parse_timezone(tz); 
  ...
}
```

to

```Rust
fn parse_timezone(tz: SqlString) -> Zone {
   ...
}

fn convert_timezone(t: Zone...) -> Option<Timestamp> {
  ...
}
```

The compiler already lifts constant expressions into lazy statics, so for the case when timezones are constant strings, this will parse each timezone only once. A similar adaptation has been made for functions that use `Regex`; these were hand-optimized previously for the case of constant regex patterns, but this way of doing things is simpler.

## Breaking changes

Regex functions (`RLIKE` and `REGEXP_REPLACE`) will now crash if the regex is not a legal Rust regex, matching the behavior of Postgres. Previously they were just ignoring malformed regexps and behaving as if there were no matches.

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java [hunk 1]
```diff
@@ -1528,15 +1548,11 @@ else if (arg0Type.is(DBSPTypeMap.class))
...
-                            DBSPStringLiteral lit = ops.get(1).to(DBSPStringLiteral.class);
-                            if (lit.isNull())
-                                return type.none();
-                            ops.set(1, this.makeRegex(lit));
-                            return compileFunction("regexp_replaceC", node, type, ops, 2, 3);
+                        for (int i = 0; i < ops.size(); i++) {
+                            if (i != 1)
+                                this.ensureString(ops, i);
                         }
+                        ops.set(1, this.makeRegex(ops.get(1)));
```
Comment (mythical-fred) [inline sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java:1555]: This change is not just a codegen cleanup; it also changes the non-constant `regexp_replace`/`RLIKE` path to go through `ParsedRegex`, which now turns an invalid pattern into a runtime failure instead of the previous fallback behavior. The tests only pin down the constant-invalid case plus one dynamic happy path. Please add coverage for invalid regex values coming from a table/expression as well, otherwise the main behavior change here is still unproven.

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java [hunk 2]
```diff
@@ -1641,8 +1657,8 @@ else if (arg0Type.is(DBSPTypeMap.class))
                     }
                     case "convert_timezone": {
                         validateArgCount(node, operationName, ops.size(), 3);
-                        ensureString(ops, 0);
-                        ensureString(ops, 1);
+                        ops.set(0, this.makeTimezone(ops.get(0)));
```
Comment (mythical-fred) [inline sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java:1660]: Same issue for timezones: after routing all `CONVERT_TIMEZONE` arguments through `parse_timezone*`, both constant and non-constant values take the new `Zone` path. The test suite covers an invalid constant timezone and a valid dynamic one, but it does not cover an invalid timezone coming from a column/expression. Since this PR changes runtime semantics in that path too, please add a non-constant invalid-timezone test before merging.

**Review by mythical-fred — CHANGES_REQUESTED** [review]
Two blockers.

File: crates/sqllib/src/string.rs [hunk 3]
```diff
@@ -722,69 +708,56 @@ pub fn to_json_nullN(_value: Option<()>) -> Option<SqlString> {
...
-some_function3!(regexp_replace3, SqlString, SqlString, SqlString, SqlString);
-
 #[doc(hidden)]
-pub fn regexp_replace2__(str: SqlString, re: SqlString) -> SqlString {
-    regexp_replace3___(str, re, SqlString::new())
+pub fn make_regex_(re: SqlString) -> ParsedRegex {
+    match Regex::new(re.str()) {
+        Ok(r) => ParsedRegex::Regex(r),
+        Err(e) => {
+            tracing::warn!(
```
Comment (gz) [inline crates/sqllib/src/string.rs]:
```suggestion
            warn!(
```

File: crates/sqllib/src/string.rs [hunk 4]
```diff
@@ -722,69 +708,56 @@ pub fn to_json_nullN(_value: Option<()>) -> Option<SqlString> {
...
+                "failed to parse '{}' as a regular expression: {}",
+                re,
+                e.to_string()
+            );
+            ParsedRegex::Invalid(re.str().to_string(), e.to_string())
```
Comment (gz) [inline crates/sqllib/src/string.rs]: re is already SqlString, can't it just stay like that in Invalid?

File: crates/sqllib/src/timestamp.rs [hunk 5]
```diff
@@ -312,27 +312,29 @@ impl Timestamp {
 
 #[doc(hidden)]
 #[derive(Debug, Clone)]
-enum Zone {
+pub enum Zone {
     Iana(Tz),
     Offset(FixedOffset),
+    // Timezone string
+    Invalid(String),
```
Comment (gz) [inline crates/sqllib/src/timestamp.rs:319]: wouldn't it be better to make those things Result<Zone, String> rather than encoding the failure case inside of Zone (and ParsedRegex)

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java [hunk 6]
```diff
@@ -722,39 +722,6 @@ public void casing() throws IOException, InterruptedException, SQLException {
...
-        try (Statement s = connection.createStatement()) {
-            s.execute("""
-                    create table mytable(
-                    id integer not null primary key,
-                    strcol varchar(25))
-                    """);
-        }
-
-        // Create a schema that retrieves data from HSQLDB
-        DataSource mockDataSource = JdbcSchema.dataSource(jdbcUrl, "org.hsqldb.jdbcDriver", "", "");
```
Comment (gz) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java:741]: can you get rid of hsqldb as a dependency now?

**Review by gz — APPROVED** [review]

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java (hunk 6 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/MetadataTests.java:741]: I think we still have a few tests that use it. Could remove it, but will it save anything?

File: crates/sqllib/src/timestamp.rs (hunk 5 above)
Comment (mihaibudiu) [reply crates/sqllib/src/timestamp.rs:319]: Could, but then the code will have `Option<Result<>>` as arguments, and I am not sure whether the macros using `?` will all work fine.
