### PR TITLE
Three commits fixing 3 different reported bugs

### LINKED ISSUE #2943: [SQL] TIMESTAMP - TIMESTAMP fails to compile
However, if we skip the unit and make it (c1-c2) it fails to compile with the following:

```sql
 Error in SQL statement:
Cannot apply '-' to arguments of type '<TIMESTAMP(0)> - <TIMESTAMP(0)>'. Supported form(s): '<NUMERIC> - <NUMERIC>'
'<DATETIME_INTERVAL> - <DATETIME_INTERVAL>'
'<DATETIME> - <DATETIME_INTERVAL>'
    2|CREATE VIEW v AS SELECT (c1 - c2) FROM x;
```

Full SQL:

```sql
CREATE TABLE x(c1 TIMESTAMP, c2 TIMESTAMP);
CREATE VIEW v AS SELECT (c1 - c2) FROM x;
```

But in our docs, we say:

TIMESTAMP - TIMESTAMP | INTERVAL (long) | Subtract two timestamps, convert result into days
-- | -- | --

_Originally posted by @abhizer in https://github.com/feldera/feldera/pull/2937#discussion_r1840299292_

### LINKED ISSUE #2946: [SQL] SELECT NULL fails to compile with NULL type must be nullable
The program:
```sql
CREATE VIEW v(c0) AS (SELECT NULL);
```

Fails with:
```java
System error: the SQL compilation failed. The compilation task produced the following output:

 Exception in thread "main" org.dbsp.sqlCompiler.compiler.errors.UnsupportedException: Null type must be nullable: 
	at org.dbsp.sqlCompiler.ir.type.primitive.DBSPTypeNull.withMayBeNull(DBSPTypeNull.java:59)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateInto(ToRustVisitor.java:165)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateFromTrait(ToRustVisitor.java:196)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateStructHelpers(ToRustVisitor.java:499)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:765)
	at org.dbsp.sqlCompiler.circuit.operator.DBSPSinkOperator.accept(DBSPSinkOperator.java:46)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateOperator(ToRustVisitor.java:357)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.processNode(ToRustVisitor.java:346)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:446)
	at org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit.accept(DBSPPartialCircuit.java:134)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:382)
	at org.dbsp.sqlCompiler.circuit.DBSPCircuit.accept(DBSPCircuit.java:60)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:81)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.toRustString(ToRustVisitor.java:1358)
	at org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter.write(RustFileWriter.java:411)
	at org.dbsp.sqlCompiler.CompilerMain.run(CompilerMain.java:222)
	at org.dbsp.sqlCompiler.CompilerMain.execute(CompilerMain.java:279)
	at org.dbsp.sqlCompiler.CompilerMain.main(CompilerMain.java:283)


Exit code: exit status: 1
```

### LINKED ISSUE #2949: [SQL] duplicate column name in view definition with named columns
Similar to #2939 but an edge case. The following program fails to compile:

```sql
CREATE TABLE t4(c0 BOOLEAN, c1 DOUBLE, c2 VARCHAR) with ('materialized' = 'true');
CREATE MATERIALIZED VIEW v1(c0, c1, c2) AS (SELECT t4.c2, t4.c0, t4.c0 FROM t4 WHERE t4.c0);
```

Fails with:

```
Duplicate column:
View 'v1' contains two columns with the same name 'c0'
You can allow this behavior using the --lenient compiler flag
    2|CREATE MATERIALIZED VIEW v1(c0, c1, c2) AS (SELECT t4.c2, t4.c0, t4.c0 FROM t4 WHERE t4.c0);
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #2943 
Fixes #2946 
Fixes #2949

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java [hunk 1]
```diff
@@ -390,4 +390,26 @@ public void testMonthDiff() {
...
+                ---------
+                 2 hours
+                (1 row)
+                
+                 select (TIMESTAMP '2024-01-01 12:00:00' - TIMESTAMP '2023-12-31 10:00:00') MINUTES;
+                 minutes
+                ---------
+                 1 day 2 hours
+                (1 row)""");
+    }
```
Comment (abhizer) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java:414]: But these outputs aren't in minutes? Or is it just the way we format it to display the result?

**Review by abhizer — APPROVED** [review]

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java (hunk 1 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/mysql/TimestampdiffTests.java:414]: Yes, these tests use the postgres serialization of intervals. We don't support intervals in views so it's not clear what the diference is between the various types of intervals
