### PR TITLE
[connectors] Fix delta table truncate mode truncating data on pipeline restart

### LINKED ISSUE #6028: bug in delta connector truncate mode
Investigate bug in the delta connector in truncate mode: it will truncate the table on each restart instead of truncating once when starting the pipeline or adding the connector.

### PR DESCRIPTION
**Pull request by swanandx**
DeltaTableWriter::new() is called every time a connector is instantiated, it unconditionally mapped DeltaTableWriteMode::Truncate to SaveMode::Overwrite , which overwrote data every time.

The controller already tracks whether a pipeline is resuming from a checkpoint via the initial_statistics parameter in add_output_endpoint() (Some when resuming, None on first start), but this information was never passed to integrated connectors.

Pass an is_restart flag from the controller through create_integrated_output_endpoint() into DeltaTableWriter::new(). When is_restart is true, use SaveMode::Ignore (open existing table as-is) instead of SaveMode::Overwrite for truncate mode. The same gate is applied to ErrorIfExists mode, which would otherwise fail on every restart since the table already exists from the first start.

For non-fault-tolerant pipelines initial_statistics is always None, so is_restart is always false and truncation happens on every explicit start

Tests use read_delta_output() which reads through the delta log rather than scanning all parquet files on disk, ensuring orphaned files left by SaveMode::Overwrite are not counted.

Fix #6028 

### Describe Manual Test Plan

created pipeline with delta output connector and verified row count in delta table using duckdb, made sure we aren't truncating data on restarts

## Checklist

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Documentation updated
- [ ] Changelog updated

## Breaking Changes?

- [x] Others (specify)

### Describe Incompatible Changes

Changes behavior of Truncate and ErrorIfExists mode ( in good way :P )

### CODE REVIEW

File: crates/adapters/src/integrated/delta_table/output.rs [hunk 1]
```diff
@@ -273,17 +274,39 @@ impl WriterTask {
...
+                    SaveMode::Overwrite
+                }
+            }
+            DeltaTableWriteMode::ErrorIfExists => {
+                if is_restart {
+                    SaveMode::Ignore
+                } else {
+                    SaveMode::ErrorIfExists
+                }
+            }
```
Comment (swanandx) [inline crates/adapters/src/integrated/delta_table/output.rs:298]: how do users use this? Is it used to detect restarts? is this intended to fail on restarts?

**Review by mythical-fred — APPROVED** [review]
LGTM

**Review by ryzhyk — CHANGES_REQUESTED** [review]
This is a good design, but there's one corner case we need to take care of. If either the connector definition or the view it is attached to has changed since the checkpoint was made, we do not currently invalidate initial_statistics for the connector. I think the correct behavior in these cases is to re-initialize the connector as if it was a new connector, which requires invalidating the stats.

This should probably happen around here: https://github.com/feldera/feldera/blob/2b36afe5c5b509349d756a0c5eb994d420a83714/crates/adapters/src/controller.rs#L4377

Related to this, we need integration tests for the delta connector. The only one we have today is `python/tests/workloads/test_tpch.py`. We should either extend that test or add a dedicated delta connector test.

As an intermediate solution, since we already have delta tests in QA, we can extend those tests to test the fix in this PR.

**Review by mythical-fred — APPROVED** [review]
LGTM

File: python/tests/platform/test_delta_output_restart.py [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+    """Unchanged pipeline: suspend+resume keeps data in the delta table."""
+    name = unique_pipeline_name("delta_restart_clean")
+    table_dir = Path(tempfile.mkdtemp(prefix="feldera_delta_test_"))
+    uri = f"file://{table_dir}"
+
+    try:
+        pipeline = _build_pipeline(name, _sql(uri=uri))
+        pipeline.start()
+        pipeline.input_json("t", [{"id": i} for i in range(50)])
+        pipeline.wait_for_idle()
```
Comment (ryzhyk) [inline python/tests/platform/test_delta_output_restart.py]: passing `wait = true` to `input_json` should block until the pipeline has written all outputs. Therefore `wait_for_idle` shouldn't be needed here and throughout this test. In fact `wait_for_idle` is an evil hack and we should avoid using it.

File: python/tests/platform/test_delta_output_restart.py [hunk 3]
```diff
@@ -0,0 +1,287 @@
...
+        # Resume with a MODIFIED connector config
+        # (extra `checkpoint_interval` field).
+        pipeline = _build_pipeline(
+            name,
+            _sql(uri=uri, extra_connector_options={"checkpoint_interval": 60}),
+        )
+        pipeline.start()
+
+        # Allow connector init + any upstream re-emission to settle.
+        pipeline.wait_for_idle()
```
Comment (ryzhyk) [inline python/tests/platform/test_delta_output_restart.py]: Likewise, the table should be truncated during initialization. If you want to make sure that the connector doesn't issue any unnecessary writes, you can just sleep for 5 more seconds.

**Review by ryzhyk — APPROVED** [review]
Looks great, thank you! I added a small comment in the Python test.

File: crates/adapters/src/integrated/delta_table/output.rs (hunk 1 above)
Comment (swanandx) [reply crates/adapters/src/integrated/delta_table/output.rs:298]: this is fine
