### PR TITLE
[SQL] Support casts to and from user-defined types

### LINKED ISSUE #2638: [sql] ICE with MAP type
This program:

```sql

CREATE TABLE t (
    m MAP<VARCHAR, VARCHAR>
) with ('materialized' = 'true');

CREATE FUNCTION map2map(i MAP<VARCHAR, VARCHAR>) RETURNS MAP<VARCHAR, VARCHAR>;
CREATE FUNCTION nmap2nmap(i MAP<VARCHAR, VARCHAR> NOT NULL) RETURNS MAP<VARCHAR, VARCHAR> NOT NULL;


CREATE MATERIALIZED VIEW v AS
SELECT
    map2map(m),
    nmap2nmap(m)
FROM
    t;
```

causes this ICE:

```
Exception in thread "main" java.lang.RuntimeException: BTreeMap<s, s?> is not an instance of class org.dbsp.sqlCompiler.ir.type.primitive.DBSPTypeBaseType
	at org.dbsp.util.ICastable.to(ICastable.java:47)
	at org.dbsp.sqlCompiler.ir.type.DBSPType.baseTypeWithSuffix(DBSPType.java:164)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:782)
	at org.dbsp.sqlCompiler.ir.expression.DBSPCastExpression.accept(DBSPCastExpression.java:107)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1057)
	at org.dbsp.sqlCompiler.ir.expression.DBSPApplyExpression.accept(DBSPApplyExpression.java:59)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1065)
	at org.dbsp.sqlCompiler.ir.expression.DBSPApplyMethodExpression.accept(DBSPApplyMethodExpression.java:62)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1356)
	at org.dbsp.sqlCompiler.ir.expression.DBSPTupleExpression.accept(DBSPTupleExpression.java:109)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustInnerVisitor.preorder(ToRustInnerVisitor.java:1161)
	at org.dbsp.sqlCompiler.ir.expression.DBSPClosureExpression.accept(DBSPClosureExpression.java:95)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:823)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.preorder(CircuitVisitor.java:122)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.preorder(CircuitVisitor.java:190)
	at org.dbsp.sqlCompiler.circuit.operator.DBSPMapOperator.accept(DBSPMapOperator.java:51)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.generateOperator(ToRustVisitor.java:351)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.processNode(ToRustVisitor.java:340)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:440)
	at org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit.accept(DBSPPartialCircuit.java:134)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.preorder(ToRustVisitor.java:376)
	at org.dbsp.sqlCompiler.circuit.DBSPCircuit.accept(DBSPCircuit.java:59)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:82)
	at org.dbsp.sqlCompiler.compiler.backend.rust.ToRustVisitor.toRustString(ToRustVisitor.java:1259)
	at org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter.write(RustFileWriter.java:412)
	at org.dbsp.sqlCompiler.CompilerMain.run(CompilerMain.java:187)
	at org.dbsp.sqlCompiler.CompilerMain.execute(CompilerMain.java:227)
	at org.dbsp.sqlCompiler.CompilerMain.main(CompilerMain.java:231)
```

Note: the second function call is invalid and should be rejected by the compiler (I think?) because the `m` column is nullable, and the function expects a non-nullable input.

### LINKED ISSUE #2639: [sql] ICE: NullPointerException compiling a udf
This program triggers a `NullPointerException` in the compiler:

```sql
CREATE TABLE t (
    bin BINARY
) with ('materialized' = 'true');

CREATE FUNCTION nbin2nbin(i BINARY NOT NULL) RETURNS BINARY NOT NULL AS i;

CREATE MATERIALIZED VIEW v AS
SELECT
    nbin2nbin(bin)
FROM
    t;
```

### LINKED ISSUE #2641: [sql] Invalid type cast causes Rust error
This program attempts to cast a date to a string (I forgot to add `DATE` to the string literal)

```sql
create table t (
    d DATE
);

create view v as select COALESCE(d, '2023-01-01') from t;
```

However, instead of rejecting the program, the compiler generates invalid Rust code?

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /working-dir/cargo_workspace/project01924970-9d07-7e90-ae28-567c1e6b5811/Cargo.toml
workspace: /working-dir/cargo_workspace/Cargo.toml
   Compiling project01924970-9d07-7e90-ae28-567c1e6b5811 v0.1.0 (/working-dir/cargo_workspace/project01924970-9d07-7e90-ae28-567c1e6b5811)
error[E0425]: cannot find function `cast_to_sN_DateN` in this scope
    --> project01924970-9d07-7e90-ae28-567c1e6b5811/src/main.rs:127:17
     |
127  |                 cast_to_sN_DateN(
     |                 ^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `cast_to_VN_DateN`
     |
    ::: /database-stream-processor/crates/sqllib/src/casts.rs:1580:1
     |
1580 | cast_variant!(Date, Date, Date);
     | ------------------------------- similarly named function `cast_to_VN_DateN` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `project01924970-9d07-7e90-ae28-567c1e6b5811` (bin "project01924970-9d07-7e90-ae28-567c1e6b5811") due to 1 previous error

```

### LINKED ISSUE #2642: [sql] Cannot coalesce VARIANT using VARIANTNULL()
```sql
create table t (
    v VARIANT
);

create view v as select COALESCE(v, VARIANTNULL()) from t;
```
causes

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /working-dir/cargo_workspace/project01924970-9d07-7e90-ae28-567c1e6b5811/Cargo.toml
workspace: /working-dir/cargo_workspace/Cargo.toml
   Compiling project01924970-9d07-7e90-ae28-567c1e6b5811 v0.1.0 (/working-dir/cargo_workspace/project01924970-9d07-7e90-ae28-567c1e6b5811)
error[E0425]: cannot find function `cast_to_V_VN` in this scope
    --> project01924970-9d07-7e90-ae28-567c1e6b5811/src/main.rs:127:17
     |
127  |                 cast_to_V_VN(
     |                 ^^^^^^^^^^^^ help: a function with a similar name exists: `cast_to_V_dN`
     |
    ::: /database-stream-processor/crates/sqllib/src/casts.rs:1577:1
     |
1577 | cast_variant_numeric!(d, F64, Double);
     | ------------------------------------- similarly named function `cast_to_V_dN` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `project01924970-9d07-7e90-ae28-567c1e6b5811` (bin "project01924970-9d07-7e90-ae28-567c1e6b5811") due to 1 previous error
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
This PR is much more involved than one would expect.
One reason is that it needs to handle not just casts from VARIANT to user-defined types, but also deeply-nested generic types that may depend on user-defined types, such as a `MAP<STRING, UDT ARRAY>`.
So the handling of casts has been revamped; casts now can convert not only the object they are applied to, but also elements of vectors (by changing nullabilities, for example).

This PR also fixes several issues related to casts:
Fixes #2639 
Fixes #2642 
Fixes #2641 
Fixes #2638

### CODE REVIEW

**Comment by mihaibudiu** [comment]
Note that Rust has some generic functions for casting vectors to variants, but these don't work when user-defined types are involved, since the TupN structs do not implement the required try_from traits.

**Comment by mihaibudiu** [comment]
A subsequent PR should remove the functions that directly convert strings to UDTs, since these can now be written as two steps: parse_json and cast.

**Comment by mihaibudiu** [comment]
@ryzhyk this is a big PR, and I re-read the code several times.
I would appreciate a review that focuses on:
- the small Rust changes
- the test files
- the documentation
- the issues fixed (all in the RegressionTests.java file)

**Comment by mihaibudiu** [comment]
Fixes #2479

File: crates/sqllib/src/casts.rs [hunk 1]
```diff
@@ -932,44 +918,51 @@ pub fn cast_to_s_Timestamp(value: Timestamp, size: i32, fixed: bool) -> String {
 }
 
 #[inline]
-pub fn cast_to_s_i(value: isize, size: i32, fixed: bool) -> String {
-    let result = value.to_string();
+pub fn cast_to_s_Date(value: Date, size: i32, fixed: bool) -> String {
+    let dt = value.to_date();
```
Comment (ryzhyk) [inline crates/sqllib/src/casts.rs:922]: chrono types have methods to serialize themselves in any format. Might have saved you a few lines of code.

File: docs/sql/json.md [hunk 2]
```diff
@@ -15,6 +15,10 @@ compare the runtime type with `T`.  If the types are identical or there
 is a natural conversion from the runtime type to `T`, the original value
 is returned.  Otherwise the `CAST` returns `NULL`.
 
+A value of type `VARIANT` that stores a `MAP` can be converted to a
+user-defined type.  Each name of a field of the user-defined type is
+used as to index into the map.
```
Comment (ryzhyk) [inline docs/sql/json.md:20]:
```suggestion
used as an index into the map.
```

Comment (ryzhyk) [reply docs/sql/json.md:20]: Describe conversion rules: map key names must match struct field names, what happens with extra keys in the map that are not in the struct, what happens with missing fields?  What happens if conversion fails. How is case sensitivity handled?

File: docs/sql/json.md [hunk 3]
```diff
@@ -369,4 +378,15 @@ SELECT TO_JSON(CAST(DATE '2020-01-01' AS VARIANT))
 -- timestamps are unparsed as strings (timezone is always +00)
 SELECT TO_JSON(CAST(TIMESTAMP '2020-01-01 10:00:00' AS VARIANT))
 "2020-01-01 10:00:00"
+
```
Comment (ryzhyk) [inline docs/sql/json.md:381]: These examples could use comments.

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java [hunk 4]
```diff
@@ -28,19 +97,10 @@ public void tableAfterView() {
     }
 
     @Test
-    public void issue2498() {
-        String sql = """
```
Comment (ryzhyk) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java:32]: Why did this go away?

**Review by ryzhyk — COMMENTED** [review]
Read the Rust code and the docs. Will test on a bigger example.

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java (hunk 4 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/RegressionTests.java:32]: because now we support these casts

**Review by ryzhyk — APPROVED** [review]
Tested on top of the UDF branch (where I ran into issues). Everything works now.
