### PR TITLE
Several SQL fixes; multiple small commits

### LINKED ISSUE #4448: Issue with TPC-H q12
This TPC-H q12 query returns an empty result:

```sql
CREATE TABLE LINEITEM (
          L_ORDERKEY    INTEGER NOT NULL,
          L_PARTKEY     INTEGER NOT NULL,
          L_SUPPKEY     INTEGER NOT NULL,
          L_LINENUMBER  INTEGER NOT NULL,
          L_QUANTITY    DECIMAL(15,2) NOT NULL,
          L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
          L_DISCOUNT    DECIMAL(15,2) NOT NULL,
          L_TAX         DECIMAL(15,2) NOT NULL,
          L_RETURNFLAG  CHAR(1) NOT NULL,
          L_LINESTATUS  CHAR(1) NOT NULL,
          L_SHIPDATE    DATE NOT NULL,
          L_COMMITDATE  DATE NOT NULL,
          L_RECEIPTDATE DATE NOT NULL,
          L_SHIPINSTRUCT CHAR(25) NOT NULL,
          L_SHIPMODE     CHAR(10) NOT NULL,
          L_COMMENT      VARCHAR(44) NOT NULL
  ) WITH (
    'materialized' = 'true',
    'connectors' = '[{
        "transport": {
        "name": "delta_table_input",
        "config": {
            "uri": "s3://batchtofeldera/lineitem",
            "aws_skip_signature": "true",
            "aws_region": "ap-southeast-2",
            "mode": "snapshot"
        }
        }
    }]'
);
  
  CREATE TABLE ORDERS  (
          O_ORDERKEY       INTEGER NOT NULL,
          O_CUSTKEY        INTEGER NOT NULL,
          O_ORDERSTATUS    CHAR(1) NOT NULL,
          O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
          O_ORDERDATE      DATE NOT NULL,
          O_ORDERPRIORITY  CHAR(15) NOT NULL,
          O_CLERK          CHAR(15) NOT NULL,
          O_SHIPPRIORITY   INTEGER NOT NULL,
          O_COMMENT        VARCHAR(79) NOT NULL
  ) WITH (
    'materialized' = 'true',
     'connectors' = '[{
        "transport": {
        "name": "delta_table_input",
        "config": {
            "uri": "s3://batchtofeldera/orders",
            "aws_skip_signature": "true",
            "aws_region": "ap-southeast-2",
            "mode": "snapshot"
        }
        }
    }]'
);

create view q12 as
select
     l_shipmode,
     sum(case
         when o_orderpriority = '1-URGENT'
             or o_orderpriority = '2-HIGH'
             then 1
         else 0
     end) as high_line_count,
     sum(case
         when o_orderpriority <> '1-URGENT'
             and o_orderpriority <> '2-HIGH'
             then 1
         else 0
     end) as low_line_count
 from
     orders,
     lineitem
 where
     o_orderkey = l_orderkey
     and l_shipmode in ('FOB', 'SHIP')
     and l_commitdate < l_receiptdate
     and l_shipdate < l_commitdate
     and l_receiptdate >= date '1994-01-01'
     and l_receiptdate < date '1994-01-01' + interval '1' year
 group by
     l_shipmode
 order by
     l_shipmode""",
```

The reason is that the generated code pads 'FOB' and 'SHIP' constants with spaces and uses precise string equality comparison.

Interestingly changing this condition
```sql
l_shipmode in ('FOB', 'SHIP')
```

to

```sql
l_shipmode in ('FOB')
```

changes the behavior (the string is no longer padded).

### LINKED ISSUE #4456: [SQL] Bug in ARRAY_COMPACT function
Following SQL:
```
CREATE TABLE tbl(arr VARCHAR ARRAY);

CREATE MATERIALIZED VIEW v AS SELECT 
ARRAY_COMPACT(arr) AS arr
FROM tbl;
```
Given example input:
**"arr": ["bye", "14", "See you!", "-0.52", None]**

Produces the following error:
```
 error[E0425]: cannot find function `array_compactN` in this scope
   --> crates/feldera_pipe_operator_9e3d756bb52ece70/src/lib.rs:72:60
    |
72  |           let p2: Tup1<Option<Array<SqlString>>> = Tup1::new(array_compactN(p1.1.as_ref().cloned()).clone());
    |                                                              ^^^^^^^^^^^^^^ help: a function with a similar name exists: `array_compact_`
    |
   ::: /Users/rivuadhikari/feldera/crates/sqllib/src/array.rs:437:1
    |
437 | / pub fn array_compact_<T>(vector: Array<Option<T>>) -> Array<T>
438 | | where
439 | |     T: Clone,
    | |_____________- similarly named function `array_compact_` defined here
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #4456 (`ARRAY_COMPACT`)
Fixes #4448 (`TRUNC`)
Warns for behavior in #4457 
Adds some tests and documentation for #4448 but not a final fix

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java [hunk 1]
```diff
@@ -999,6 +999,7 @@ node, new DBSPTypeBool(CalciteObject.EMPTY, false), DBSPOpcode.EQ,
             case OTHER_FUNCTION: {
                 String opName = call.op.getName().toLowerCase();
                 switch (opName) {
+                    case "trunc":
```
Comment (ryzhyk) [inline sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java:1002]: Maybe also fixup documentation to make it clear that TRUNC is a synonym of TRUNCATE, since currently they look like two different functions.

File: docs.feldera.com/docs/sql/types.md [hunk 2]
```diff
@@ -17,7 +17,7 @@ The compiler supports the following SQL data types:
 | `REAL`                      | IEEE 32-bit floating point number                                                                                                                                  | `FLOAT4`, `FLOAT32`        |
 | `DOUBLE`                    | IEEE 64-bit floating point number                                                                                                                                  | `FLOAT8`, `FLOAT64`        |
 | `VARCHAR(n)`                | A string value with maximum fixed width. Trailing spaces are removed when converting a value to this type.                                                         | `CHARACTER VARYING(n)`     |
-| `CHAR(n)`                   | A string value with a fixed width. Values are truncated if longer, or padded with spaces if shorter, to be brought to the specified size.                          | `CHARACTER(n)`             |
+| `CHAR(n)`                   | A string value with a fixed width. Values are truncated if longer, or padded with spaces if shorter, to be brought to the specified size. We recommend against using CHAR(n) columns.  | `CHARACTER(n)`             |
```
Comment (ryzhyk) [inline docs.feldera.com/docs/sql/types.md]:
```suggestion
| `CHAR(n)`                   | A string value with a fixed width. Values are truncated if longer, or padded with spaces if shorter, to be brought to the specified size. This type is supported for legacy reasons; we recommend using `VARCHAR` intead. See [below](...).  | `CHARACTER(n)`             |
```

**Review by ryzhyk — APPROVED** [review]

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java (hunk 1 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/ExpressionCompiler.java:1002]: that's what the documentation says:
> same as TRUNCATE(value [, digits]) (result is a DECIMAL value).
