### PR TITLE
[SQL] Two optimizations in separate commits; advance Calcite

### LINKED ISSUE #5113: [SQL] MAP constructor does not support VARIANT values
The following program crashes in Calcite:

```sql
CREATE TABLE T (r VARCHAR(255) NOT NULL, f VARIANT);
CREATE VIEW V AS SELECT MAP[
   'a', CAST(r AS VARIANT),
   'b', f
] FROM T;
```

The stack trace is:

```sql
java.lang.UnsupportedOperationException: Unsupported type when convertTypeToSpec: VARIANT

	at org.apache.calcite.sql.type.SqlTypeUtil.convertTypeToSpec(SqlTypeUtil.java:1368)
	at org.apache.calcite.sql.type.SqlTypeUtil.convertTypeToSpec(SqlTypeUtil.java:1391)
	at org.apache.calcite.sql.validate.SqlValidatorUtil.castTo(SqlValidatorUtil.java:1487)
	at org.apache.calcite.sql.validate.SqlValidatorUtil.adjustTypeForMultisetConstructor(SqlValidatorUtil.java:1468)
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #5113

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java [hunk 1]
```diff
@@ -1650,4 +1651,37 @@ FROM S, UNNEST(S.v) WITH ORDINALITY AS t(a, b)
...
+                CREATE FUNCTION CONVERT_TIMESTAMP(d VARCHAR)
+                RETURNS TIMESTAMP
+                AS ( IF( d IS NULL, NULL, COALESCE(
+                    -- ISO 8601 formats with timezone (Z suffix)
+                    PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S Z', d),
+                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%S.%3fZ', d),
+                    PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', d))));
+                CREATE VIEW V AS SELECT CONVERT_TIMESTAMP('2020-01-01 10:00:00');""");
+        // CSE should ensure that there are only 3 calls to parse_timestamp;
+        // without it, there would be 6 calls.
```
Comment (lalithsuresh) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java:1667]: Why would there be 6 calls without CSE?

**Review by ryzhyk — APPROVED** [review]

**Review by ryzhyk — APPROVED** [review]
