### PR TITLE
[adapters] Fix delta suspend test.

### LINKED ISSUE #4097: [ADAPTERS] Fix and enable failing test `delta_table_snapshot_and_follow_file_test_suspend`
This test was disabled to merge PR #4087

### PR DESCRIPTION
**Pull request by ryzhyk**
Fixes #4097.

The tests suspended the pipeline without waiting for the first input batch to be fully processed.

### CODE REVIEW

File: crates/adapters/src/integrated/delta_table/test.rs [hunk 1]
```diff
@@ -741,6 +741,22 @@ async fn test_follow(
 
     let mut total_count = split_at;
 
+    let expected_output = data[0..total_count]
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/test.rs:744]: how on earth did this ever pass previously?

**Review by mihaibudiu — APPROVED** [review]
