### PR TITLE
Make Delta connectors robust to S3 timeouts.

### LINKED ISSUE #4739: [adapters] Make Delta connectors robust to S3 timeouts
Collecting various issues related to transient Delta input/output connector errors:

I'm not sure if the following situation can still occur after recent object-store improvements:

Today, if the delta input connector fails to read a transaction log entry (usually due to a transient S3 error), it reports an error an continues. As a result, data from this log entry will not get ingested. This can only be corrected with some manual fixup. Instead, the pipeline should retry reading the failed log entry a configurable number of times (possibly, indefinitely).

Note that this can lead to duplicate inputs, but most pipelines should be able to tolerate that.

### PR DESCRIPTION
**Pull request by ryzhyk**
See individual commits for details.

Fixes #4739

### CODE REVIEW

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 1]
```diff
@@ -48,14 +49,20 @@ use tokio::select;
...
 use url::Url;
 
 /// Polling interval when following a delta table.
 const POLL_INTERVAL: Duration = Duration::from_millis(1000);
 
-/// Polling delay before retrying an unsuccessful read from a delta log.
-const RETRY_INTERVAL: Duration = Duration::from_millis(2000);
+/// Calculate exponential backoff delay for retrying delta log reads.
+/// Starts at 0.5s, doubles each retry, caps at 32s.
+fn calculate_backoff_delay(retry_count: u32) -> Duration {
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:60]: I have seen lots of similar code, should this be encapsulated in a struct which everyone should use?
the struct could have the bounds, the nature of the backoff, and keep the retry_count, and could include a sleep method.

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 2]
```diff
@@ -797,13 +807,25 @@ impl DeltaTableInputEndpointInner {
...
-
-                        sleep(RETRY_INTERVAL).await;
+                        // Transient timeouts are common when reading the next log entry from S3.
+                        retry_count += 1;
+
+                        if retry_count == 20 {
+                            self.consumer.error(
+                                true,
+                                anyhow!("error reading the next log entry after {retry_count} attempts (current table version: {version}): {e}"),
+                                Some("delta-next-log")
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:817]: what is "delta-next-log"?

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 3]
```diff
@@ -827,70 +849,126 @@ impl DeltaTableInputEndpointInner {
...
+            // (see https://github.com/delta-io/delta-rs/issues/3768). So we add a timeout and retry logic
+            // in that case.
+            //
+            // In other situations, the operation fails returning a timeout error. There is no easy way to
+            // distinguish such errors from permanent failures such as incorrect credentials, we therefore
+            // resort to checking the returned error message for the word "timeout".
+            let mut operation_timeout: Duration = Duration::from_secs(60);
+
+            loop {
+                // DeltaTableBuilder doesn't implement Clone, so we need to create a new instance every time.
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:866]: has anyone filed an issue about this?

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 4]
```diff
@@ -827,70 +849,126 @@ impl DeltaTableInputEndpointInner {
...
+
+                match tokio::time::timeout(operation_timeout, table_builder.load()).await {
+                    Ok(Ok(table)) => break table,
+                    Ok(Err(e)) => {
+                        // Debug-format `e` as the timeout error is often found toward the end of the error chain.
+                        let is_timeout = format!("{:?}", e).to_lowercase().contains("timeout");
+
+                        if is_timeout && retry_count < MAX_RETRIES {
+                            retry_count += 1;
+                            let backoff_ms = min(1000 * (1 << (retry_count - 1)), 10_000);
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:932]: told you so

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 5]
```diff
@@ -827,70 +849,126 @@ impl DeltaTableInputEndpointInner {
...
+                                    root_cause(&e)
+                                ),
+                            ));
+                        }
+                    }
+                    Err(_timeout) => {
+                        if retry_count >= MAX_RETRIES {
+                            return Err(ControllerError::invalid_transport_configuration(
+                                &self.endpoint_name,
+                                &format!(
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:955]: should this include the last error received?

File: crates/adapters/src/integrated/delta_table/output.rs [hunk 6]
```diff
@@ -275,18 +276,70 @@ impl WriterTask {
...
+                    .with_location(inner.config.uri.clone())
+                    .with_save_mode(save_mode)
+                    .with_storage_options(storage_options.clone())
+                    .with_columns(inner.struct_fields.clone());
+
+                match tokio::time::timeout(operation_timeout, create_future).await {
+                    Ok(Ok(table)) => break table,
+                    Ok(Err(e)) => {
+                        // Debug-format `e` as the timeout error is often found toward the end of the error chain.
+                        let is_timeout = format!("{:?}", e).to_lowercase().contains("timeout");
```
[the remark this answers is not in the document]
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/output.rs:303]: The comment in the code explains why it has to be this way.

File: crates/adapters/src/integrated/delta_table/input.rs (hunk 1 above)
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/input.rs:60]: I'll use the backoff crate

File: crates/adapters/src/integrated/delta_table/input.rs (hunk 5 above)
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/input.rs:955]: there's no error in this branch - this is the problem it just doesn't return in some cases, we don't know why, but I filed an issue with delta-rs

File: crates/adapters/src/integrated/delta_table/input.rs (hunk 2 above)
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/input.rs:817]: Tag for rate limiting.

File: crates/adapters/src/integrated/delta_table/input.rs (hunk 1 above)
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/input.rs:60]: meh, it doesn't quite fit in the other situations because of the two different kinds of timeouts we're dealing with
