### PR TITLE
[SQL] Vec/Map/ZSet/Variant expressions are not always literals (#3164)

### LINKED ISSUE #3164: Lateness bounds with tumbling window and emit_final
**Describe the bug**
Not sure it's a bug or I'm missing something, but I would expect the emission of values with emit_final to account for possible late values, which seems to not be the case (at least with my current parameters).

I have lateness configured on input ts of 15s. Then I have some processing and a tumbling window over 1 min and finally an output view with emit_final annotation. See below full SQL for reference. 

However the emission of the final table occurs always exactly at the 0th second of the new minute, so any late arrival data which would still respect the lateness bounds is arriving late.

One thing to note is I had to explicitly also declare lateness for window_end on the final view as the compiler was not deducing it automatically.

**To Reproduce**

Send the following input messages:
```bash
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:50:00","peer_src":"10.100.100.1","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":1,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.11"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:50:30","peer_src":"10.100.100.2","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":2,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.12"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:51:01","peer_src":"10.100.100.3","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":3,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.13"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:50:55","peer_src":"10.100.100.4","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":4,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.14"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:51:02","peer_src":"10.100.100.5","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":5,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.15"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:51:15","peer_src":"10.100.100.6","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":6,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.16"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:51:30","peer_src":"10.100.100.7","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":7,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.17"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:50:59","peer_src":"10.100.100.8","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":8,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.18"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:52:10","peer_src":"10.100.100.9","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":9,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.19"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
curl -i -X POST 'http://localhost:8080/v0/pipelines/vmware/ingress/flows?format=json' -d '{"insert":{"ts":"2024-10-25 11:52:30","peer_src":"10.100.100.10","writer_id":"crafted-messages","payload":{"IPFIX":{"version":10,"export_time":"2024-10-25T11:00:00Z","sequence_number":10,"observation_domain_id":1,"sets":[{"Data":{"id":347,"records":[{"scope_fields":[],"fields":[{"packetDeltaCount":1},{"octetDeltaCount":10},{"sourceIPv4Address":"192.0.2.20"},{"destinationIPv4Address":"192.0.2.17"}]}]}}]}}}}'
```

Two messages are late: 4 (within lateness bounds, waterline at 11:51:01) and 8 (outside lateness bounds, since waterline is already at 11:51:30).
With the example messages provided, the tumbling window is changing correctly and lateness is respected there: message 4 is considered, while message 8 is discarded (see screenshot below).
However the final view is emitted exactly when window_end is sliding to the next minute without accounting for possibly late arriving data.
Thus the late arrival message is never being emitted, since the window for that minute was already emitted before.

Output (as you see we miss the message with ip_src=192.0.2.14 which is the one arriving late but within the lateness bounds):
```json
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.11"},"packets":{"long":1},"peer_ip_src":"10.100.100.1","sequence_number":{"long":1},"timestamp_max":1729857000000000,"timestamp_min":1729857000000000,"window_end":1729857060000000,"window_start":1729857000000000}
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.12"},"packets":{"long":1},"peer_ip_src":"10.100.100.2","sequence_number":{"long":2},"timestamp_max":1729857030000000,"timestamp_min":1729857030000000,"window_end":1729857060000000,"window_start":1729857000000000}
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.13"},"packets":{"long":1},"peer_ip_src":"10.100.100.3","sequence_number":{"long":3},"timestamp_max":1729857061000000,"timestamp_min":1729857061000000,"window_end":1729857120000000,"window_start":1729857060000000}
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.15"},"packets":{"long":1},"peer_ip_src":"10.100.100.5","sequence_number":{"long":5},"timestamp_max":1729857062000000,"timestamp_min":1729857062000000,"window_end":1729857120000000,"window_start":1729857060000000}
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.16"},"packets":{"long":1},"peer_ip_src":"10.100.100.6","sequence_number":{"long":6},"timestamp_max":1729857075000000,"timestamp_min":1729857075000000,"window_end":1729857120000000,"window_start":1729857060000000}
{"bytes":{"long":10},"flows":null,"ip_proto":null,"ip_src":{"string":"192.0.2.17"},"packets":{"long":1},"peer_ip_src":"10.100.100.7","sequence_number":{"long":7},"timestamp_max":1729857090000000,"timestamp_min":1729857090000000,"window_end":1729857120000000,"window_start":1729857060000000}
```

**Screenshots**

Change streams view:
image

**Context (please complete the following information):**
 - Feldera Version: 0.32.0, bfac5a9c8bd6c19fc1a86
 - Environment: Native
 - Browser: Chrome
 - Pipeline Configuration/SQL code:

SQL:
``` sql
CREATE FUNCTION array_to_map(input VARIANT ARRAY) RETURNS VARIANT NOT NULL;

-- Input Table for flows
CREATE TABLE flows (
    ts TIMESTAMP NOT NULL LATENESS INTERVAL 15 SECONDS,
    peer_src VARCHAR NOT NULL,
    writer_id VARCHAR NOT NULL,
    payload VARIANT
)
WITH (
    'append_only' = 'true'
);

-- Extract the top-level fields and unnest the 'sets' field in the message into multiple rows
CREATE VIEW first_pass AS
    SELECT
        ts,
        peer_src,
        writer_id,
        CAST(payload['IPFIX']['sequence_number'] AS BIGINT) AS sequence_number,
        CAST(payload['IPFIX']['observation_domain_id'] AS BIGINT) AS observation_domain_id,
        flow_set
    FROM
        flows,
        UNNEST(CAST(payload['IPFIX']['sets'] AS VARIANT ARRAY)) as t (flow_set);


-- Flatten ['Data']['records'], and group scope_fields and fields into MAP
CREATE VIEW flattened_data AS
    SELECT
        ts,
        peer_src,
        writer_id,
        sequence_number,
        observation_domain_id,
        flow_set['Data']['id'] as data_id,
        array_to_map(CAST(record['scope_fields'] AS VARIANT ARRAY)) as scope_fields,
        array_to_map(CAST(record['fields'] AS VARIANT ARRAY)) as fields
    FROM
        first_pass,
        UNNEST(CAST(flow_set['Data']['records'] AS VARIANT ARRAY)) as t (record);

-- Extract IPFIX fields we need
CREATE VIEW flattened AS
    SELECT
        ts,
        peer_src,
        writer_id,
        sequence_number,
        observation_domain_id,
        CAST(fields['octetDeltaCount'][1] AS BIGINT) as octetDeltaCount,
        CAST(fields['packetDeltaCount'][1] AS BIGINT) as packetDeltaCount,
        CAST(fields['deltaFlowCount'][1] AS BIGINT) as deltaFlowCount,
        CAST(fields['sourceIPv4Address'][1] AS VARCHAR) as sourceIPAddress,
        CAST(fields['destinationIPv4Address'][1] AS VARCHAR) as destinationIPAddress,
        CAST(fields['protocolIdentifier'][1] AS INTEGER) as protocolIdentifier
    FROM flattened_data;

-- Create a tumbling window view for aggregating
CREATE VIEW tumble (
    ts_min,
    ts_max,
    window_start,
    window_end,
    peer_src,
    sequence_number,
    packetDeltaCount,
    octetDeltaCount,
    deltaFlowCount,
    sourceIPAddress,
    protocolIdentifier
)
AS
    SELECT
            MIN(ts) AS ts_min,
            MAX(ts) AS ts_max,
            window_start,
            window_end,
            peer_src,
            MAX(sequence_number) AS sequence_number,
            SUM(packetDeltaCount) AS packetDeltaCount,
            SUM(octetDeltaCount) AS octetDeltaCount,
            SUM(deltaFlowCount) AS deltaFlowCount,
            sourceIPAddress,
            protocolIdentifier
    FROM TABLE(
        TUMBLE(
            TABLE flattened,
            DESCRIPTOR(ts),
            INTERVAL '1' MINUTES
        )
    )
    GROUP BY
        window_start, window_end,
        peer_src, writer_id, observation_domain_id,
        sourceIPAddress, destinationIPAddress, protocolIdentifier

    -- Filter out templates and option records (retain only data records)
    HAVING sourceIPAddress IS NOT NULL;

-- Create the final view with the translation logic
LATENESS final.window_end INTERVAL 15 SECONDS;
CREATE VIEW final
    WITH (
        'connectors' = '[
            {
                "transport": {
                    "name": "kafka_output",
                    "config": {
                        "bootstrap.servers": "localhost:49092",
                        "topic": "feldera_flow"
                    }
                },
                "format": {
                    "name": "avro",
                    "config": {
                        "update_format": "raw",
                        "registry_urls": ["http://localhost:48081"]
                    }
                }
           }
        ]',
        'emit_final' = 'window_end'
    )
    AS SELECT
        ts_min as timestamp_min,
        ts_max as timestamp_max,
        window_start,
        window_end,
        peer_src AS peer_ip_src,
        sequence_number,
        packetDeltaCount AS packets,
        octetDeltaCount AS bytes,
        deltaFlowCount AS flows,
        sourceIPAddress AS ip_src,
        protocolIdentifier AS ip_proto
    FROM tumble;

```

UDFs:
```rust
// Deps for udf.toml:
// chrono="0.4.38"

use chrono::NaiveDateTime;
use feldera_sqllib::*;
use std::collections::BTreeMap;

// Convert array of maps into map with arrays as values to handle duplicated values
pub fn array_to_map(
    input_vec: Option<Vec<Option<Variant>>>,
) -> Result<Variant, Box<dyn std::error::Error>> {

    let input_vec = match input_vec {
        Some(vec) => vec,
        None => return Err("UDFs[array_to_map]: empty input".into()),
    };

    let mut ret = BTreeMap::new();

    for element in input_vec {
        let element = match element {
            Some(e) => e,
            None => return Err("UDFs[array_to_map]: found None value in input vec".into()),
        };
        let map = match element {
            Variant::Map(map) => map,
            _ => return Err("UDFs[array_to_map]: found unsupported variant type".into()),
        };
        for (k, v) in map {
            ret.entry(k).or_insert(vec![]).push(v);
        }
    }

    // Build map output
    let x = ret
        .into_iter()
        .map(|(k, v)| {
            if v.iter().all(|item| matches!(item, Variant::Map(_))) {
                // Recursively call the function to handle nested maps
                let nested_map = array_to_map(Some(v.into_iter().map(Some).collect()))?;
                Ok((k, nested_map))
            } else {
                Ok((k, Variant::Array(v)))
            }
        })
        .collect::<Result<BTreeMap<Variant, Variant>, Box<dyn std::error::Error>>>()?;

    Ok(Variant::Map(x))
}

```

**Additional context**

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #3164 

This is a cleanup which I wanted to do a long time ago. Since now it triggered a bug, it was a good time to do it.
Basically, expressions like DBSPMapLiteral were constructor invocations, and not necessarily literals, since some arguments may not be constant.

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java [hunk 1]
```diff
@@ -26,6 +26,170 @@ public DBSPCompiler testCompiler() {
         return new DBSPCompiler(options);
     }
 
+    @Test
+    public void issue3164() {
+        this.getCCS("""
+               CREATE FUNCTION parse_ts(input VARCHAR) RETURNS TIMESTAMP NOT NULL;
```
Comment (ryzhyk) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/simple/IncrementalRegressionTests.java:32]: maybe the test could be simplified. You probably don't need all this for a minimal repro.

**Review by ryzhyk — APPROVED** [review]
