### PR TITLE
adapters: enable unity catalog feature for deltalake

### LINKED ISSUE #4695: Support ingesting Delta Tables from Unity Catalogs
# Summary
[summary]: #summary

The underlying library that you guys use to interact with delta lakes supports reading directly from unity catalogs: https://github.com/delta-io/delta-rs/issues/3276

But for some reason this doesn't work with Feldera.

Please, allow this to function.

E.g attempting to set `uri` to some unity catalog:
```
CREATE TABLE transaction(
    ...
) WITH (
  'connectors' = '[{
    "transport": {
      "name": "delta_table_input",
      "config": {
        "uri": "uc://{catalog}.{schema}.{table}",
      }
    }
  }
]');
```

Should work.

### PR DESCRIPTION
**Pull request by swanandx**
Fixes #4695 

## Checklist

- [x] Documentation updated
- [ ] Changelog updated

( where to update em? )

## Breaking Changes?

No. 

Adding support for unity catalog should not break any _existing_ functionality

### CODE REVIEW

**Comment by brurucy** [comment]
Awesome. Lmk when it is merged. I can test it right away (tomorrow).

**Comment by ryzhyk** [comment]
> A test would be nice. Something more to worry about breaking stuff.

Yep needs tests and possibly additional config options. Will try to find time to work on this over the next several days.

File: crates/adapters/src/integrated/delta_table/input.rs [hunk 1]
```diff
@@ -265,6 +267,18 @@ impl DeltaTableInputReader {
             inner: endpoint.clone(),
         })
     }
+
+    /// deltalake_catalog_unity expects all configuration settings to be provided as environment variables.
+    /// This function sets environment variables for all configuration settings that start with "unity_" or "databricks_".
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/input.rs:272]: (case insensitive)

File: crates/adapters/src/integrated/delta_table/test.rs [hunk 2]
```diff
@@ -1714,3 +1719,49 @@ fn delta_table_s3_people_2m() {
...
+    .collect::<HashMap<_, _>>();
+
+    let table_uri = "uc://feldera_experimental.default.people_2m";
+    let mut json_file = delta_table_snapshot_to_json::<DatabricksPeople>(
+        table_uri,
+        &DatabricksPeople::schema(),
+        &object_store_config,
+    );
+
+    println!("reading output file");
```
Comment (mihaibudiu) [inline crates/adapters/src/integrated/delta_table/test.rs:1757]: it this supposed to be left in?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 3]
```diff
@@ -21,7 +24,7 @@ exactly once fault tolerance.
 
 | Property                    | Type   | Default    | Description   |
 |-----------------------------|--------|------------|---------------|
-| `uri`*                      | string |            | Table URI, e.g., "s3://feldera-fraud-detection-data/demographics_train"|
+| `uri`*                      | string |            | Table URI, e.g., `s3://feldera-fraud-detection-data/demographics_train`. Supported URI schemes include: <ul><li>AWS S3: `s3://`, `s3a://`</li><li>Azure Blob Storage: `az://`, `adl://`, `azure://`, `abfs://`, `abfss://`</li><li>Google Cloud Storage: `gs://`</li><li>`uc://` - Unity catalog</li></ul> |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md:27]: I hope markdown tables support nested html; in my tables I had to use `<table>`

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 4]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+or as environment variables set inside the pipeline pod. If the same option is specified
+in both places, the connector property takes precedence.
+
+<Tabs>
+    <TabItem value="s3" label="Amazon S3">
+The following configuration options are supported for Amazon S3 object store. See [`object_store` documentation](https://docs.rs/object_store/latest/object_store/aws/enum.AmazonS3ConfigKey.html) for additional details.
+
+| Configuration Option                                                      | Environment Variable                     | Description                                                                       |
+| ------------------------------------------------------------------------- | ---------------------------------------- | --------------------------------------------------------------------------------- |
+| `aws_access_key_id`, `access_key_id`                                      | `AWS_ACCESS_KEY_ID`                      | AWS access key ID for authentication.                                             |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md:56]: I wonder what happens if multiple of these exist with conflicting values

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 5]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `aws_skip_signature`, `skip_signature`                                    | `AWS_SKIP_SIGNATURE`                     | If enabled, AmazonS3 will not fetch credentials and will not sign requests. This can be useful when interacting with public S3 buckets that deny authorized requests |
+| `aws_imdsv1_fallback`, `imdsv1_fallback`                                  | `AWS_IMDSV1_FALLBACK`                    | Enable automatic fallback to using IMDSv1 if the token endpoint returns a 403 error indicating that IMDSv2 is not supported. |
+| `aws_virtual_hosted_style_request`, `virtual_hosted_style_request`        | `AWS_VIRTUAL_HOSTED_STYLE_REQUEST`       | Sets if virtual hosted style request has to be used. If `false` (default), path style request is used, if `true`, virtual hosted style request is used. If the endpoint is provided then it should be consistent with virtual_hosted_style_request. i.e. if virtual_hosted_style_request is set to true then endpoint should have bucket name included.|
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md]: "sets if ..." is awkward. Sets the virtual hosted request setting?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 6]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `aws_unsigned_payload`, `unsigned_payload`                                | `AWS_UNSIGNED_PAYLOAD`                   | Avoid computing payload checksum when calculating signature.                      |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md:64]: terrible name choice. unsigned is used for something else everywhere.
what is wrong with not_signed?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 7]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `azure_storage_client_id`, `azure_client_id`, `client_id`                 | `AZURE_STORAGE_CLIENT_ID`                | Service principal client id for authorizing requests.                             |
+| `azure_storage_client_secret`, `azure_client_secret`, `client_secret`     | `AZURE_STORAGE_CLIENT_SECRET`            | Service principal client secret for authorizing requests.                         |
+| `azure_storage_tenant_id`, `azure_storage_authority_id`, `azure_tenant_id`, `azure_authority_id`, `tenant_id`, `authority_id`| `AZURE_STORAGE_TENANT_ID`| Tenant id used in oauth flows.                 |
+| `azure_storage_authority_host`, `azure_authority_host`, `authority_host`  | `AZURE_STORAGE_AUTHORITY_HOST`, `AZURE_AUTHORITY_HOST`| Authority host used in oauth flows.                                  |
+| `azure_storage_sas_key`, `azure_storage_sas_token`, `sas_key`, `sas_token`| `AZURE_STORAGE_SAS_KEY`, `AZURE_STORAGE_SAS_TOKEN`| Shared access signature. The signature is expected to be percent-encoded, much like they are provided in the azure storage explorer or azure portal.|
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md]: they are -> it is?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 8]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `azure_storage_endpoint`, `azure_endpoint`, `endpoint`                    | `AZURE_STORAGE_ENDPOINT`, `AZURE_ENDPOINT` | Override the endpoint used to communicate with blob storage.                    |
+| `azure_use_fabric_endpoint`, `use_fabric_endpoint`                        | `AZURE_USE_FABRIC_ENDPOINT`              | Use object store with url scheme `account.dfs.fabric.microsoft.com`               |
+| `azure_msi_endpoint`, `azure_identity_endpoint`, `identity_endpoint`, `msi_endpoint`| `AZURE_MSI_ENDPOINT`, `AZURE_IDENTITY_ENDPOINT`| Endpoint to request a imds managed identity token.                |
+| `azure_object_id`, `object_id`                                            | `AZURE_OBJECT_ID`                        | Object id for use with managed identity authentication.                           |
+| `azure_msi_resource_id`, `msi_resource_id`                                | `AZURE_MSI_RESOURCE_ID`                  | Msi resource id for use with managed identity authentication.                     |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md:96]: should the last MSI be capitalized?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 9]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `unity_client_id`, `databricks_client_id`                                 | `UNITY_CLIENT_ID`, `DATABRICKS_CLIENT_ID`| Service principal client id for authorizing requests.                             |
+| `unity_client_secret`, `databricks_client_secret`                         | `UNITY_CLIENT_SECRET`, `DATABRICKS_CLIENT_SECRET`| Service principal client secret for authorizing requests.                 |
+| `unity_tenant_id`, `databricks_tenant_id`                                 | `UNITY_TENANT_ID`, `DATABRICKS_TENANT_ID`| Authority (tenant) id used in oauth flows.                                        |
+| `unity_authority_host`, `databricks_authority_host`                       | `UNITY_AUTHORITY_HOST`, `DATABRICKS_AUTHORITY_HOST`| Authority host used in oauth flows.                                     |
+| `unity_msi_endpoint`, `databricks_msi_endpoint`                           | `UNITY_MSI_ENDPOINT`, `DATABRICKS_MSI_ENDPOINT` | Endpoint to request a imds managed identity token.                         |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md]: an imds?
Should IMDS be capitalized?

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 10]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `unity_object_id`, `databricks_object_id`                                 | `UNITY_OBJECT_ID`, `DATABRICKS_OBJECT_ID`| Object id for use with managed identity authentication.                           |
+| `unity_msi_resource_id`, `databricks_msi_resource_id`                     | `UNITY_MSI_RESOURCE_ID`, `DATABRICKS_MSI_RESOURCE_ID`| Msi resource id for use with managed identity authentication.         |
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md]: same question about MSI

File: docs.feldera.com/docs/connectors/sources/delta.md [hunk 11]
```diff
@@ -40,11 +43,130 @@ exactly once fault tolerance.
...
+| `unity_federated_token_file`, `databricks_federated_token_file`           | `UNITY_FEDERATED_TOKEN_FILE`, `DATABRICKS_FEDERATED_TOKEN_FILE`| File containing token for Azure AD workload identity federation.|
```
Comment (mihaibudiu) [inline docs.feldera.com/docs/connectors/sources/delta.md:138]: this is called Unity but only handles Azure?

File: crates/adapters/src/integrated/delta_table/test.rs (hunk 2 above)
Comment (ryzhyk) [reply crates/adapters/src/integrated/delta_table/test.rs:1757]: this is testing code. No harm in leaving it.

File: docs.feldera.com/docs/connectors/sources/delta.md (hunk 3 above)
Comment (ryzhyk) [reply docs.feldera.com/docs/connectors/sources/delta.md:27]: yes, this works

File: docs.feldera.com/docs/connectors/sources/delta.md (hunk 4 above)
Comment (ryzhyk) [reply docs.feldera.com/docs/connectors/sources/delta.md:56]: Explicit settings take precedence over env variables. But if you specify multiple values for the same field, only one gets picked up, but unfortunately we don't throw an error (I just checked this).

File: docs.feldera.com/docs/connectors/sources/delta.md (hunk 6 above)
Comment (ryzhyk) [reply docs.feldera.com/docs/connectors/sources/delta.md:64]: Not my choice.
