### PR TITLE
SQL: Beta-reduction should substitute a deepCopy of the argument expression

### LINKED ISSUE #740: SQL compiler `RuntimeException` when generating JIT IR.
The following program was obtained by adding `7 as seven` to the `artifact_vulnerability` view:

```sql
-- CI/CD pipeline.
create table pipeline (
    pipeline_id bigint not null,
    create_date timestamp not null,
    createdby_user_id bigint not null,
    update_date timestamp,
    updatedby_user_id bigint
);

-- Git commits used by each pipeline.
create table pipeline_sources (
    git_commit_id bigint not null,
    pipeline_id bigint not null foreign key references pipeline(pipeline_id)
);

-- Binary artifact created by a CI pipeline.
create table artifact (
    artifact_id bigint not null,
    artifact_uri varchar not null,
    create_date timestamp not null,
    createdby_user_id bigint not null,
    checksum varchar not null,
    checksum_type varchar not null,
    artifact_size_in_bytes bigint not null,
    artifact_type varchar not null,
    builtby_pipeline_id bigint not null foreign key references pipeline(pipeline_id),
    parent_artifact_id bigint foreign key references artifact(artifact_id)
);

-- Vulnerabilities discovered in source code.
create table vulnerability (
    vulnerability_id bigint not null,
    discovery_date timestamp not null,
    discovered_by_user_id bigint not null,
    discovered_in bigint not null,
    update_date timestamp,
    updated_by_user_id bigint,
    checksum varchar not null,
    checksum_type varchar not null,
    vulnerability_reference_id varchar not null,
    severity int,
    priority varchar
);

-- K8s clusters.
create table k8scluster (
    k8scluster_id bigint not null,
    k8s_uri varchar not null,
    name varchar not null,
    k8s_service_provider varchar not null
);


-- Deployed k8s objects.
create table k8sobject (
    k8sobject_id bigint not null,
    artifact_id bigint not null foreign key references artifact(artifact_id),
    create_date timestamp not null,
    createdby_user_id bigint not null,
    update_date timestamp,
    updatedby_user_id bigint,
    checksum varchar not null,
    checksum_type varchar not null,
    deployed_id bigint not null foreign key references k8scluster(k8scluster_id),
    deployment_type varchar not null,
    k8snamespace varchar not null
);

-- Vulnerabilities that affect each pipeline.
create view pipeline_vulnerability (
    pipeline_id,
    vulnerability_id
) as
    SELECT pipeline_sources.pipeline_id as pipeline_id, vulnerability.vulnerability_id as vulnerability_id FROM
    pipeline_sources
    INNER JOIN
    vulnerability
    ON pipeline_sources.git_commit_id = vulnerability.discovered_in;

-- Vulnerabilities that affect each artifact.
create view artifact_vulnerability (
    artifact_id,
    vulnerability_id,
    seven
) as
    SELECT artifact.artifact_id as artifact_id, pipeline_vulnerability.vulnerability_id as vulnerability_id, 7 as seven FROM
    artifact
    INNER JOIN
    pipeline_vulnerability
    ON artifact.builtby_pipeline_id = pipeline_vulnerability.pipeline_id;

-- Vulnerabilities in the artifact or any of its children.
create view transitive_artifact_vulnerability(
    artifact_id,
    via_artifact_id,
    vulnerability_id
) as
    SELECT artifact_id, artifact_id as via_artifact_id, vulnerability_id from artifact_vulnerability
    UNION
    (
        SELECT
            artifact.parent_artifact_id as artifact_id,
            artifact.artifact_id as via_artifact_id,
            artifact_vulnerability.vulnerability_id as vulnerability_id FROM
        artifact
        INNER JOIN
        artifact_vulnerability
        ON artifact.artifact_id = artifact_vulnerability.artifact_id
        WHERE artifact.parent_artifact_id IS NOT NULL
    );

-- Vulnerabilities that affect each k8s object.
create view k8sobject_vulnerability (
    k8sobject_id,
    vulnerability_id
) as
    SELECT k8sobject.k8sobject_id, transitive_artifact_vulnerability.vulnerability_id FROM
    k8sobject
    INNER JOIN
    transitive_artifact_vulnerability
    ON k8sobject.artifact_id = transitive_artifact_vulnerability.artifact_id;

-- Vulnerabilities that affect each k8s cluster.
create view k8scluster_vulnerability (
    k8scluster_id,
    vulnerability_id
) as
    SELECT
        k8sobject.deployed_id as k8scluster_id,
        k8sobject_vulnerability.vulnerability_id FROM
    k8sobject_vulnerability
    INNER JOIN
    k8sobject
    ON k8sobject_vulnerability.k8sobject_id = k8sobject.k8sobject_id;

-- Per-cluster statistics:
-- * Number of vulnerabilities.
-- * Most severe vulnerability.
create view k8scluster_vulnerability_stats (
    k8scluster_id,
    k8scluster_name,
    total_vulnerabilities,
    most_severe_vulnerability
) as
    SELECT
        cluster_id,
        k8scluster.name as k8scluster_name,
        total_vulnerabilities,
        most_severe_vulnerability
    FROM
    (
        SELECT
            cluster_id,
            COUNT(*) as total_vulnerabilities,
            MAX(severity) as most_severe_vulnerability
        FROM
        (
            SELECT k8scluster_vulnerability.k8scluster_id as cluster_id, vulnerability.vulnerability_id, vulnerability.severity FROM
            k8scluster_vulnerability
            INNER JOIN
            vulnerability
            ON k8scluster_vulnerability.vulnerability_id = vulnerability.vulnerability_id
        )
        GROUP BY cluster_id
    )
    INNER JOIN
    k8scluster
    ON k8scluster.k8scluster_id = cluster_id;
```

Command line and exception:

```bash
$ ../../../sql-to-dbsp-compiler/SQL-compiler/sql-to-dbsp -js schema.json  -i -j -alltables project.sql  > ir.json
Exception in thread "main" java.lang.RuntimeException: Key 599 already mapped to 3:# when adding 5:#
	at org.dbsp.util.Utilities.putNew(Utilities.java:98)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.map(ToJitInnerVisitor.java:288)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.preorder(ToJitInnerVisitor.java:1190)
	at org.dbsp.sqlCompiler.ir.expression.DBSPFieldExpression.accept(DBSPFieldExpression.java:75)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.accept(ToJitInnerVisitor.java:296)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.preorder(ToJitInnerVisitor.java:1319)
	at org.dbsp.sqlCompiler.compiler.visitors.inner.InnerVisitor.preorder(InnerVisitor.java:428)
	at org.dbsp.sqlCompiler.ir.expression.DBSPTupleExpression.accept(DBSPTupleExpression.java:110)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.preorder(ToJitInnerVisitor.java:1345)
	at org.dbsp.sqlCompiler.compiler.visitors.inner.InnerVisitor.preorder(InnerVisitor.java:428)
	at org.dbsp.sqlCompiler.ir.expression.DBSPTupleExpression.accept(DBSPTupleExpression.java:110)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.preorder(ToJitInnerVisitor.java:1423)
	at org.dbsp.sqlCompiler.ir.expression.DBSPBlockExpression.accept(DBSPBlockExpression.java:51)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.preorder(ToJitInnerVisitor.java:1142)
	at org.dbsp.sqlCompiler.ir.expression.DBSPClosureExpression.accept(DBSPClosureExpression.java:71)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitInnerVisitor.convertClosure(ToJitInnerVisitor.java:1455)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitVisitor.convertFunction(ToJitVisitor.java:136)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitVisitor$OperatorConversion.<init>(ToJitVisitor.java:90)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitVisitor.preorder(ToJitVisitor.java:282)
	at org.dbsp.sqlCompiler.circuit.operator.DBSPMapOperator.accept(DBSPMapOperator.java:52)
	at org.dbsp.sqlCompiler.circuit.DBSPPartialCircuit.accept(DBSPPartialCircuit.java:106)
	at org.dbsp.sqlCompiler.circuit.DBSPCircuit.accept(DBSPCircuit.java:59)
	at org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor.apply(CircuitVisitor.java:76)
	at org.dbsp.sqlCompiler.compiler.backend.jit.ToJitVisitor.circuitToJIT(ToJitVisitor.java:557)
	at org.dbsp.sqlCompiler.CompilerMain.run(CompilerMain.java:156)
	at org.dbsp.sqlCompiler.CompilerMain.execute(CompilerMain.java:177)
	at org.dbsp.sqlCompiler.CompilerMain.main(CompilerMain.java:181)
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #740

### CODE REVIEW

**Comment by mihaibudiu** [comment]
The compiler makes an implicit assumption that no expression sub-trees are shared, i.e., the IR is a tree and not a DAG. Substitution could violate this invariant, so we make a deep copy when needed.

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java [hunk 1]
```diff
@@ -242,6 +244,185 @@ public void testComplex() throws IOException, InterruptedException {
         Utilities.compileAndTestRust(rustDirectory, true);
     }
 
+    // Test case for issue 740
+    @Test
```
Comment (lalithsuresh) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java:248]: You probably want a more minimal test case too. I believe it's just "7 as seven" that triggers the bug right?

**Review by lalithsuresh — APPROVED** [review]

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java (hunk 1 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java:248]: I am not sure what does, didn't have time to reduce it.
But I don't see why that would have this effect.

Comment (lalithsuresh) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java:248]: As per the issue, it's the only addition to the program that was otherwise compiling fine: https://github.com/feldera/feldera/issues/740

Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/ComplexQueriesTest.java:248]: yes, but I don't think it's in the inner select that the problem happens.
too tired to reduce the case now.
