### PR TITLE
Fix missing syntax highlight in SQL editor

### LINKED ISSUE #6101: [WEBCONSOLE] Syntax highlighting has disappeared
https://amd64-eks.staging.feldera.io/

### PR DESCRIPTION
**Pull request by Karakatiza666**
Remove unnecessary monaco-editor devDependency from forked monaco-editor-vite-plugin which breaks syntax highlight - single-line fix, `package.json#L37` + `bun.lock`. The rest of the changes are just touching up the fork source files - project setup (package.json), add extra comments from the original (index.ts).

Fix https://github.com/feldera/feldera/issues/6101

## Testing

Manual testing. I filed an [issue](https://github.com/feldera/feldera/issues/6105) to add a regression test for syntax highlight. I need to configure screenshot comparison for this, this is something I was unable to do in expected time frame before.

## The bug
 
  After switching web-console's vite plugin import from @bithero/monaco-editor-vite-plugin to the local @feldera/ fork, syntax highlighting for SQL (and other non-default languages) stopped working, even though the plugin's source is a near-verbatim copy of upstream.

### The root cause
                  
  The plugin injects language contribution imports by calling import.meta.resolve('monaco-editor/esm/...') inside its load() hook. That resolves relative to the real path of the plugin module, not the symlink path consumers see.

  Two monaco-editor versions were installed in the tree:

  - js-packages/web-console/node_modules/monaco-editor → 0.55.1 (web-console's direct dependency)
  - js-packages/monaco-editor-vite-plugin/node_modules/monaco-editor → 0.55.0 (pulled in by the fork's own devDependencies entry)

  The original package worked because it was installed as a plain package inside web-console/node_modules/@bithero/, so resolution walked up to web-console's 0.55.1. @feldera/ is a bun workspace symlink into js-packages/monaco-editor-vite-plugin/, so resolution walked up from the real path and hit the fork's locally-nested 0.55.0 first.

  The result: language contribution modules registered themselves into monaco 0.55.0's ModesRegistry singleton, while the editor the app actually renders is 0.55.1 — so SQL, Rust, and GraphQL contributions were never visible to the running editor.
 
### The fix

  Drop monaco-editor from the fork's devDependencies. It's already declared as a peerDependency, which is all the plugin needs for typechecking. Without the nested install, the plugin's existing process.cwd() fallback resolves monaco from the consumer (web-console), keeping plugin and app on the same monaco instance.

### CODE REVIEW

File: js-packages/monaco-editor-vite-plugin/src/index.ts [hunk 1]
```diff
@@ -146,11 +196,24 @@ function resolveWorkers(
   return workers
 }
 
+/**
+ * Resolves an module path by utilising `import.meta.resolve`, but making sure we're returning
```
Comment (mihaibudiu) [inline js-packages/monaco-editor-vite-plugin/src/index.ts]: a

File: js-packages/monaco-editor-vite-plugin/src/index.ts [hunk 2]
```diff
@@ -146,11 +196,24 @@ function resolveWorkers(
...
+ * @param file the filepath to resolve
+ * @return the resolved path
+ */
 function resolveModule(file: string): string {
   const url = import.meta.resolve(file).toString()
   return url.replace(/^file:\/\//, '')
 }
 
+/**
+ * Resolves an file path either against the monaco-editor esm package, or by itself.
```
Comment (mihaibudiu) [inline js-packages/monaco-editor-vite-plugin/src/index.ts]: same

File: js-packages/monaco-editor-vite-plugin/src/index.ts [hunk 3]
```diff
@@ -198,6 +268,20 @@ export function monaco(options?: MonacoOptions): Plugin {
         const result = [
           `// Generated by @feldera/monaco-editor-vite-plugin`,
           `// SPDX-License-Identifier: AGPL-3.0-or-later`,
+          `// `,
```
Comment (mihaibudiu) [inline js-packages/monaco-editor-vite-plugin/src/index.ts]: was this missing by mistake?

**Review by mihaibudiu — APPROVED** [review]

File: js-packages/monaco-editor-vite-plugin/src/index.ts [hunk 4]
```diff
@@ -212,12 +296,10 @@ export function monaco(options?: MonacoOptions): Plugin {
           })(${workerPathsJson});`,
           ...features
             .flatMap((feature) => feature.entry)
-            .filter((entry): entry is string => !!entry)
-            .map((entry) => `import "${resolveMonacoPath(entry)}";`),
+            .map((entry) => `import "${resolveMonacoPath(entry as string)}";`),
```
Comment (mythical-fred) [inline js-packages/monaco-editor-vite-plugin/src/index.ts]: Nit: the old code filtered out nullish entries before resolving; the new code casts blindly with `as string`. If any feature/language metadata entry is ever `null`/`undefined`, this will pass `"undefined"` to `resolveMonacoPath`. Probably fine in practice (monaco metadata is well-typed), but the old `.filter` was safer.

File: js-packages/monaco-editor-vite-plugin/src/index.ts [hunk 5]
```diff
@@ -182,6 +251,7 @@ export function monaco(options?: MonacoOptions): Plugin {
       }
       optimizeDeps.exclude.push('monaco-editor')
       if (optimizeDeps.include) {
+        console.log("[feldera-monaco] removed 'monaco-editor' from the optimizeDeps.include setting.")
```
Comment (mythical-fred) [inline js-packages/monaco-editor-vite-plugin/src/index.ts]: Nit: `console.log` in a vite plugin — consider removing or gating behind a `verbose` option so it doesn't spam every build.

**Review by mythical-fred — APPROVED** [review]
LGTM

**Comment by Karakatiza666** [comment]
Removed the fork of the bithero/monaco-editor-vite-plugin NPM package.

Added a new @feldera/vite-plugin-monaco-editor package that correctly tree-shakes both the monaco workers and features, resulting in ~0.8 MB savings in a non-compressed production web-console bundle.

Testing: manually tested the used code editor features: syntax highlight, search-and-replace, parent scope block folding (at the top of the editor), minimap.

File: js-packages/vite-plugin-monaco-editor/src/index.ts [hunk 6]
```diff
@@ -0,0 +1,365 @@
...
+}
+
+// Paths inside bare side-effect imports that represent editor contribs and
+// standalone add-ons. These are the ones we want to gate through the user's
+// `features` selection rather than have every language/worker file pull them
+// in unconditionally.
+const CONTRIB_IMPORT_RE =
+  /(?:\.\.[/\\])+editor[/\\](?:contrib|standalone[/\\]browser)[/\\][^'"]+/
+
+function stripContribSideEffectImports(
```
Comment (mythical-fred) [inline js-packages/vite-plugin-monaco-editor/src/index.ts:262]: This strips contrib side-effect imports across monaco files, which can change editor behavior (features now only load if explicitly listed). The web-console has zero tests, so behavior changes need coverage. Please add tests for the plugin (e.g., validate load() removes contrib imports and preserves selected languages/features) or an equivalent integration test.

**Review by mythical-fred — CHANGES_REQUESTED** [review]
Request changes: behavior change without tests (see inline). Also fix commit message typos in "Remove forked vite-pugin-moaco-editor" (pugin→plugin, moaco→monaco).
