### PR TITLE
[SQL] Additional validation for default values

### LINKED ISSUE #3615: Errors Inserting with DEFAULT Columns
**Describe the bug**
Inserting values with defaults defined on a column fail with an error.

**To Reproduce**
1. Create a new Feldera Pipeline.
2. Add the `program.sql` below to it.
```
CREATE TABLE example (
    inserted_xid BIGINT not null,
    deleted_xid BIGINT not null default '9223372036854775807'
);
```
3. `INSERT INTO example (inserted_xid) VALUES (1);` in the Adhoc Query window.
Image

4. See error --> `FATAL error on input endpoint 'adhoc-ingress-example-d8e97873-7967-4504-b626-12ca024668c3': Execution error: Invalid batch column at '1' has null but schema specifies non-nullable`
**Expected behavior**
I expected the insert to behave as a normal SQL insert with the default honored.

**Screenshots**
See screenshot above.

**Context (please complete the following information):**
 - Feldera Version: 0.37.0
 - Environment: docker (image `ghcr.io/feldera/pipeline-manager:0.37.0`)
 - Browser: chrome
 - Pipeline Configuration/SQL code: (see above)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mihaibudiu**
Not enough to resolve #3615

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java [hunk 1]
```diff
@@ -24,6 +24,15 @@ public CompilerOptions testOptions(boolean incremental, boolean optimize) {
         return result;
     }
 
+    @Test
+    public void issue3615() {
+        this.statementsFailingInCompilation("""
+                CREATE TABLE example (
+                    inserted_xid BIGINT not null,
+                    deleted_xid BIGINT not null default null -- '9223372036854775807'
+                );""", "Nullable default value assigned to non-null column 'deleted_xid'");
```
Comment (ryzhyk) [inline sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java:33]: Shouldn't it be "Null is a assigned as a default value to non-null column XXX"? Are there other nullable values that are not NULL?

Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java:33]: Could be a function call in the future

Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/CatalogTests.java:33]: Or an expression of the other columns

**Review by ryzhyk — APPROVED** [review]
