### PR TITLE
[SQL] Increase the macro expansion recursion size for operators with wide star joins

### LINKED ISSUE #6150: [SQL] Very wide "star" joins fail in Rust compilation
```
error: recursion limit reached while expanding `$crate::count_tts!`
  --> crates/feldera_pipe_operator_9e997d714f5fbef1/src/lib.rs:69:1
   |
69 | define_inner_star_join_index!(140);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`feldera_pipe_operator_9e997d714f5fbef1`)
   = note: this error originates in the macro `$crate::count_tts` which comes from the expansion of the macro `define_inner_star_join_index` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The solution is to rewrite such joins into trees of narrower joins.

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #6150

### Describe Manual Test Plan

There is a unit test.
I have also tested this with the web-ui.

This fix is not the one suggested in the issue: it does not break wide joins into multiple joins. It just increases the macro expansion limit for Rust. We already do that for wide tuples, so the same procedure is followed for wide joins.

### CODE REVIEW

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/SingleOperatorWriter.java [hunk 1]
```diff
@@ -88,6 +88,16 @@ public void write(DBSPCompiler compiler) {
         this.operator.accept(findOuterResources);
 
         boolean useHandles = compiler.options.ioOptions.emitHandles;
+
+        long limit = used.getRecursionLimit();
+        if (limit > 240) {
+            // this is just a guess
+            this.builder().append("#![recursion_limit = \"")
```
Comment (gz) [inline sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/SingleOperatorWriter.java:95]: what crazy sql causes this

**Review by gz — APPROVED** [review]

File: sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/SingleOperatorWriter.java (hunk 1 above)
Comment (mihaibudiu) [reply sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/multi/SingleOperatorWriter.java:95]: For example computing 140 MAX aggregates within the same SELECT. There is a test case which generates exactly this pattern.
