### PR TITLE
[dbsp] Fix deadlock w multiple recursive fragments

### LINKED ISSUE #4168: [dbsp] Deadlock with recursive circuits.
This line can deadlock when the circuit has multiple independent recursive fragments. If different workers start executing different recursive fragments at the same time, they will deadlock waiting for each other.

https://github.com/feldera/feldera/blob/118eebc307530a714916f21656157094e6ed9368/crates/dbsp/src/circuit/circuit_builder.rs#L3868

### PR DESCRIPTION
**Pull request by ryzhyk**
Fixes #4168.

A DBSP circuit with multiple independent recursive fragments (which schedulable at the same time) could deadlock.

What happened:
- Worker thread 1 starts executing recursive fragment 1.
- At the end of each iteration it checks termination condition, which requires waiting for a notification from all other workers.
- Worker thread 2 picks a different recursive fragment and blocks waiting for a notification from thread 1.

The fix uses async notifications instead of sync blocking, which allows the circuit to continue evaluating other operators while waiting for other threads. This way in the above scenario worker 1 can evaluate the second recursive fragment and unblock worker 2.

### CODE REVIEW

File: crates/dbsp/src/operator/dynamic/recursive.rs [hunk 1]
```diff
@@ -245,6 +249,62 @@ mod test {
...
+
+        let start = Instant::now();
+        while start.elapsed() < Duration::from_secs(100) {
+            if handle.is_finished() {
+                handle.join().unwrap();
+                return;
+            }
+            thread::sleep(Duration::from_millis(100));
+        }
+
```
Comment (mihaibudiu) [inline crates/dbsp/src/operator/dynamic/recursive.rs:304]: Is this test deterministically deadlocking in the absence of this fix? Or is it a race?

**Review by mihaibudiu — APPROVED** [review]

File: crates/dbsp/src/operator/dynamic/recursive.rs (hunk 1 above)
Comment (ryzhyk) [reply crates/dbsp/src/operator/dynamic/recursive.rs:304]: It's a race, but it's easy to reproduce.

Comment (ryzhyk) [reply crates/dbsp/src/operator/dynamic/recursive.rs:304]: This test specifically was failing every time for me without the fix.
